version: '3.1'

services:

  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: probono
      POSTGRES_USERNAME: probono
      PGDATABASE: probono
      PGUSER: probono
      PGPASSWORD: probono
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes: 
      - /var/run/postgresql:/var/run/postgresql
      - /var/lib/postgresql:/var/lib/postgresql/data
  backend:
    image: mathwww/probono-backend
    ports:
      - "3333:3333"
    environment:
      DATABASE_HOST: db
    networks:
      - postgres-network
    depends_on:
      - db
  frontend:
    image: mathwww/probono-frontend
    ports:
      - "3000:3000"
    networks:
      - postgres-network
    depends_on:
      - backend
networks:
  postgres-network:
    driver: bridge
